# -*- coding: utf-8 -*-
"""Jutyer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vWUgUKVMREkHx2OP7wuEGjKb34EflyX
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels (2).csv']))
display(df)

df = df.replace(',', '')
display(df)

import plotly.express as px

##The histogram displays the count of the amount of channels that possess a specific amount of subscibers

fig = px.histogram(df, x='Video count', title='Video Count ')
fig.show()

# Shows the distribution of categories based on teh amount of channels provided

px.pie(df, values='started', names='category', title='Subscribers by Year Started ')
fig.show()

#Shows the distribution of youtube channel creation

import plotly.express as px

fig = px.box(df, y='started', title='Years Started')
fig.show()
